name: MHPlotModeration
main: com.minehut.moderators.plotmoderation.PlotModeration
version: 1.2.1
api-version: 1.21
description: Used to make plot moderation easier on the Minehut build contest server.
depend:
  - PlotSquared